import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./assets/globals.css";
import Header from "@/components/Header";

import Footer from "@/components/Footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className + ' ' + 'bg-ble-400'} >
        <Header />
        <div className="">{children}</div>
        <Footer/>
      </body>
    </html>
  );
}
